name = "BeyondNothing-Simplified"
license = "MIT"
licenselink = "https://den.dev"
description = "Simplified theme inspired by the work done on BeyondNothing."
homepage = "https://den.dev/"
min_version = 0.1
tags = ["blog", "minimalist", "clean"]
features = "Not available."